### ISSUE TITLE
can't find runKF()

### ISSUE THREAD

**Issue by ElizabethFerriss** [FRBNY-TimeSeriesAnalysis/Nowcasting#2]
Line 241 of dfm.m reads % Note: Kalman filter (runKF()) is in the 'functions' folder, but I don't see runKF in the functions folder.

**Comment by devon-ge** [comment]
See Line 816 in the same file (`dfm.m`).

**Comment by ElizabethFerriss** [comment]
Ah, I see it now. Thank you.
