### ISSUE TITLE
Daily and Weekly data incorporation

### ISSUE THREAD

**Issue by AJKBajwa** [FRBNY-TimeSeriesAnalysis/Nowcasting#5]
Dear @brandynbok and @eric-qian ,

Thank you for this code. You have done an amazing work. 

I am currently trying to incorporate daily and weekly data into the current model. The research paper by Modugno is a bit difficult to understand. 

In the code :
You give a tent type structure from quarterly to monthly
r_mat = [2, -1, 0, 0, 0; 3, 0, -1, 0, 0; 2, 0, 0, -1, 0; 1, 0, 0, 0, -1]

Could you explain where this come from and how I can change this for my daily/ weekly model.

**Comment by eric-qian** [comment]
Hi @AJKBajwa, thank you for your interest! The tent structure is simply a product of the first order log-approximation of growth rates. Mariano and Murasawa (2003) contains a more in-depth discussion (see https://onlinelibrary.wiley.com/doi/abs/10.1002/jae.695 for details). 

In principle, a similar scheme could be used for higher frequencies.
